### ISSUE TITLE
Failing to fill-in non-title provinces for maps with large numbers of counties

### ISSUE THREAD

**Issue by malonkey1** [ParadoxGameConverters/MapDegrader#11]
It's me again! Having an issue where the mapdegrader doesn't successfully fill in the non-title provinces for counties, instead sort of just striping them diagonally.

I can't really _prove_ off-hand that it's because of the large province count, but since this issue only started occurring after we had added more provinces to our map, that's the only explanation I can think of. Attached is a compressed archive file containing the files used with the degrader and it's exported results if you want to verify for yourself.

[MapDegrader.zip](https://github.com/ParadoxGameConverters/MapDegrader/files/10496613/MapDegrader.zip)

**Comment by Zemurin** [comment]
Nah, you're feeding it crap. Watch:

![image](https://user-images.githubusercontent.com/2392697/214535633-7f898824-d4d2-4574-b2da-8a44936dc747.png)

See the FF column? That's your opacity/alpha layer. Since PDX provinces.bmp/png should never contain transparency degrader doesn't account for that so that's why it processes every 4th pixel - it grabs 3 bytes at a time, and every 4th grab actually matches original pixel.

Drop the 32-bit color or resave to png or something.

**Comment by malonkey1** [comment]
I see, thank you.
